# MODEL KLASIFIKASI

In [1]:
import pandas as pd
from sklearn.naive_bayes import MultinomialNB, BernoulliNB
from sklearn.svm import LinearSVC
from sklearn.neural_network import multilayer_perceptron
from sklearn.feature_extraction.text import TfidfVectorizer,CountVectorizer,TfidfTransformer
from sklearn.cross_validation import train_test_split
import pandas as pd
from sklearn.pipeline import Pipeline
from sklearn.naive_bayes import MultinomialNB

# from sklearn.cross_validation import cross_val_score, cross_val_predict
from sklearn import metrics
# Perform 5-fold cross validation
from sklearn.model_selection import KFold
from sklearn.metrics import accuracy_score
from sklearn.model_selection import cross_val_score


C:\Users\7\Anaconda2\envs\py27\lib\site-packages\sklearn\cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


In [2]:
df = pd.read_csv('data sentiment/dataModelClean.csv', encoding='utf-8')
df.head()

created                                               text actual
0  8/2/2018 2:29  memang cirihas alir korupsi kampret tidak kuti...    neg
1  8/2/2018 2:44    begal tewas kan gapapa kejam lindung anak istri    neg
2  8/2/2018 4:22  uu ite edit foto bunuh karakter penjara berapa...    pos
3  8/2/2018 4:22  buset baca thread nya rasa pingin ngamuk mba p...    neg
4  8/2/2018 4:24               lurah banyuwangi hasil selamat bunuh    pos

In [3]:
from sklearn.feature_extraction.text import CountVectorizer
count_vect = CountVectorizer()
X_train_counts = count_vect.fit_transform(df.text)
#print X_train_counts.shape
#count_vect.vocabulary_

In [4]:
from sklearn.feature_extraction.text import TfidfTransformer
tfidf_transformer = TfidfTransformer()
X_train_tfidf = tfidf_transformer.fit_transform(X_train_counts)
print X_train_tfidf.shape
print(tfidf_transformer.fit_transform(count_vect.fit_transform(df.text)).toarray())

(4024, 7631)
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [5]:
nb = MultinomialNB()

In [6]:
# from sklearn.model_selection import KFold
df_actual = df['actual']
data_X = X_train_tfidf
kf = KFold(n_splits=10)
for train, test in kf.split(data_X):
    #print("%s %s\n " % (train, test))
    X = X_train_tfidf
    y = df_actual
    print train
    print test
    X_train1, X_test1, y_train1, y_test1 = X[train], X[test], y[train], y[test]
    print("Size of training set: {} size of test set: {}\n".format(X_train1.shape, X_test1.shape))

scores = cross_val_score(nb, X_train_tfidf, y, cv=10)
print "Cross-validated scores :", scores
    

[ 403  404  405 ... 4021 4022 4023]
[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161
 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179
 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197
 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215
 216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233
 234 235 236 23

In [11]:
# from sklearn.preprocessing import LabelBinarizer
# import numpy as np

# lb = LabelBinarizer()
# y_test1 = np.array([number[0] for number in lb.fit_transform(y_test1)])
# recall = cross_val_score(nb, X_test1, y_test1, cv=10, scoring='recall')
# print('Recall Mean : ', np.mean(recall))


In [12]:
# precision = cross_val_score(nb, X_test1, y_test1, cv=10, scoring='precision')
# print('Precision Mean : ', np.mean(precision))

In [13]:
# f1 = cross_val_score(nb, X_train1, y_train, cv=10, scoring='f1')
# print('fscore Mean : ', np.mean(f1))

In [14]:
performance_model = []

from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
import pickle
i = 0
kf = KFold(n_splits=10)
for train, test in kf.split(data_X):
    X = X_train_tfidf
    y = df_actual
    X_train, X_test, y_train, y_test = X[train], X[test], y[train], y[test]
    model_combine_feature = nb.fit(X_train,y_train)
    print"classification_report", classification_report(model_combine_feature.predict(X_test),y_test)
    report = classification_report(model_combine_feature.predict(X_test),y_test)
    report = report.split()
    performance_model.append([report[17],report[18],report[19]])
    with open('model_combine '+ str(i)+'.pkl ', 'wb') as f:
        pickle.dump(model_combine_feature, f)
        print('model combine feature',i,' saved in', './model.pkl',i)
        i+= 1


classification_report              precision    recall  f1-score   support

        neg       0.98      0.75      0.85       367
        pos       0.25      0.83      0.38        36

avg / total       0.91      0.76      0.81       403

('model combine feature', 0, ' saved in', './model.pkl', 0)
classification_report              precision    recall  f1-score   support

        neg       0.98      0.83      0.90       366
        pos       0.34      0.84      0.48        37

avg / total       0.92      0.83      0.86       403

('model combine feature', 1, ' saved in', './model.pkl', 1)
classification_report              precision    recall  f1-score   support

        neg       0.98      0.71      0.82       382
        pos       0.12      0.71      0.20        21

avg / total       0.93      0.71      0.79       403

('model combine feature', 2, ' saved in', './model.pkl', 2)
classification_report              precision    recall  f1-score   support

        neg       0.97      0.81 

In [15]:
a = pd.DataFrame(performance_model)
a.columns = ['precision','recall','f1-score']
a

precision recall f1-score
0      0.91   0.76     0.81
1      0.92   0.83     0.86
2      0.93   0.71     0.79
3      0.89   0.82     0.84
4      0.83   0.71     0.73
5      0.86   0.72     0.75
6      0.87   0.78     0.80
7      0.91   0.86     0.87
8      0.96   0.88     0.91
9      0.95   0.93     0.94

# TEST DATA

In [12]:
#load model
import pickle
import pandas as pd
filename1='model_combine 9.pkl'
loaded_model = pickle.load(open(filename1, 'rb'))

In [13]:
df = pd.read_csv('data sentiment/dataModelClean.csv', encoding='utf-8')
df.head()

created                                               text actual
0  8/2/2018 2:29  memang cirihas alir korupsi kampret tidak kuti...    neg
1  8/2/2018 2:44    begal tewas kan gapapa kejam lindung anak istri    neg
2  8/2/2018 4:22  uu ite edit foto bunuh karakter penjara berapa...    pos
3  8/2/2018 4:22  buset baca thread nya rasa pingin ngamuk mba p...    neg
4  8/2/2018 4:24               lurah banyuwangi hasil selamat bunuh    pos

In [14]:
count_vect = CountVectorizer()
X_train_counts = count_vect.fit_transform(df.text)
#print X_train_counts.shape
#count_vect.vocabulary_

In [15]:
from sklearn.feature_extraction.text import TfidfTransformer
tfidf_transformer = TfidfTransformer()
X_train_tfidf = tfidf_transformer.fit_transform(X_train_counts)
print X_train_tfidf.shape
print(tfidf_transformer.fit_transform(count_vect.fit_transform(df.text)).toarray())

(4024, 7631)
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [16]:
df1 = pd.read_csv('data sentiment/dataTestClean.csv', encoding='utf-8')
df1.head()

no                                               text
0   1  cara teknis begal jalan ambil motor ngambilnya...
1   2  bukan jalan klompok begal intan klompok begal ...
2   3   jatuh kabur begal massa aksi lapang golf ciperna
3   4  pria korban begal desa sidogiri pasuruan desac...
4   5  begal rajalela jalan krakatau pukul korban mas...

In [17]:
X_testcv = count_vect.transform(df1.text)

In [18]:
predict_test = loaded_model.predict(X_testcv)
print predict_test

[u'neg' u'neg' u'neg' u'neg' u'neg' u'neg' u'neg' u'neg' u'neg' u'neg'
 u'neg' u'neg' u'neg' u'neg' u'neg' u'neg' u'neg' u'neg' u'neg' u'neg'
 u'neg' u'neg' u'neg' u'neg' u'neg' u'pos' u'neg' u'neg' u'neg' u'neg'
 u'neg' u'neg' u'neg' u'neg' u'neg' u'neg' u'neg' u'neg' u'neg' u'neg'
 u'neg' u'neg' u'neg' u'neg' u'pos' u'neg' u'pos' u'pos' u'pos' u'pos'
 u'pos' u'neg' u'pos' u'pos' u'pos' u'neg' u'pos' u'neg' u'neg' u'neg'
 u'pos' u'neg' u'pos' u'neg' u'neg' u'neg' u'neg' u'neg' u'pos' u'neg'
 u'pos' u'pos' u'pos' u'neg' u'neg' u'neg' u'neg' u'neg' u'neg' u'neg'
 u'neg' u'neg' u'neg' u'pos' u'pos' u'pos' u'neg' u'neg' u'neg' u'neg'
 u'neg' u'neg' u'neg' u'pos' u'pos' u'neg' u'neg' u'neg' u'neg' u'pos'
 u'pos' u'pos' u'pos' u'pos' u'pos' u'pos' u'neg' u'neg' u'neg' u'pos'
 u'neg' u'neg' u'neg' u'neg' u'neg' u'neg' u'neg' u'neg' u'pos' u'neg'
 u'neg' u'neg' u'neg' u'neg' u'neg' u'neg' u'pos' u'neg' u'pos' u'neg'
 u'neg' u'neg' u'pos' u'neg' u'pos' u'neg' u'neg' u'neg' u'pos' u'neg'
 u'neg

In [19]:
import csv
from collections import defaultdict



text = df1['text']
no = df1['no']


In [20]:
tweet = {'text':text, 'sentiment':predict_test}
frame = pd.DataFrame(tweet , columns = ['text','sentiment'])
print (frame)

                                                  text sentiment
0    cara teknis begal jalan ambil motor ngambilnya...       neg
1    bukan jalan klompok begal intan klompok begal ...       neg
2     jatuh kabur begal massa aksi lapang golf ciperna       neg
3    pria korban begal desa sidogiri pasuruan desac...       neg
4    begal rajalela jalan krakatau pukul korban mas...       neg
5                begal payudara aksi modus bekap remas       neg
6    karyawan indomaret korban begal begalmotor wal...       neg
7                          aksi begal motor satu tewas       neg
8    begal medan manuver jalan kota terang terang g...       neg
9    daerah simalingkar begal makin parah seram pul...       neg
10   banyak begal solusi untk aman kota medan janga...       neg
11        ikut lokasi rawan begal medan hati hati bung       neg
12          liat lihat kemaren berita tipu olshop soal       neg
13   bodoh ngakunya bap nyata tipu publik biar liha...       neg
14   lihat kasus tipu mar

In [21]:
frame.to_csv("hasil Sentiment.csv", index=False)

In [22]:
hasil = pd.read_csv("hasil Sentiment.csv")
hasil.set_index("sentiment", inplace=True)
negative = hasil.drop('pos')
negative.to_csv('hasilSentimentNegative.csv')

In [23]:
kembalikan = pd.read_csv('kembalikanTest.csv')
#frameNo = frame['no']
frameSentiment = frame['sentiment']
kembalikanText = kembalikan['text']

tweet = {'text':kembalikanText, 'sentiment':frameSentiment}
frames=pd.DataFrame(tweet, columns=['text','sentiment'])
frames.to_csv('tampilkanSentiment.csv', index=False)

In [24]:
frames1=pd.read_csv('tampilkanSentiment.csv')
frames1.set_index("sentiment", inplace=True)
negative1 = frames1.drop('pos')
negative1.to_csv('hasilSentimentNegativeAsli.csv')

# EVALUASI DATA TEST

In [27]:
#evaluasi data Test
testData=pd.read_csv("evaluasiTest.csv")
testData.head()
print len(testData)

362


In [28]:
actual = testData['actual']
predicted = testData['pred']
print('confusion matrix')
accuracy = accuracy_score(actual, predicted)
print 'The resulting accuracy using Multinaivebayes is ', (100 * accuracy), '%\n'
print(metrics.confusion_matrix(actual, predicted))


confusion matrix
The resulting accuracy using Multinaivebayes is  87.56906077348067 %

[[261  31]
 [ 14  56]]


In [29]:
from sklearn import metrics
print('classification report')
print(metrics.classification_report(actual, predicted))

classification report
             precision    recall  f1-score   support

        neg       0.95      0.89      0.92       292
        pos       0.64      0.80      0.71        70

avg / total       0.89      0.88      0.88       362

